import { toNano, Address, SendMode, beginCell } from '@ton/core';
import { envContent } from '../utils/jetton-helpers';
import { FossFiConfig, storeTopUp, TopUp } from '../wrappers/fi/FossFi';
import { getJettonHttpLink, getNetworkFromEnv } from '../utils/utils';
import { printSeparator } from '../utils/print';
// import "dotenv/config";

import { FossFi } from '../wrappers/fi/FossFi';
import { compile, NetworkProvider } from '@ton/blueprint';

export async function run(provider: NetworkProvider) {
    const deployer = process.env.DEPLOYER;
    if (deployer === undefined) {
        console.error("deployer address is not provided, please add it to .env file")
        throw new Error("deployer address is not provided")
    }
    const deployerAddress = Address.parse(deployer);
    // ====================================================================================
    const walletCode = await compile('FossFiWallet')
    const lotteryCode = await compile('Lottery')


    const otherCodes = beginCell()
        .storeRef(lotteryCode)
        .storeRef(beginCell().endCell())
        .storeRef(beginCell().endCell())
        .storeRef(beginCell().endCell())
        .endCell()

    const fossFiConfig: FossFiConfig = {
        supply: 0n,
        walletVersion: 0n,
        admin: deployerAddress,
        // lottery: null, // no lottery for now
        base_fi_wallet_code: walletCode,
        latest_fi_wallet_code: walletCode,
        metadata: envContent, // content
        others: otherCodes,
    };

    const fossFi = provider.open(FossFi.createFromConfig(fossFiConfig, await compile('FossFi')));

    await fossFi.sendDeploy(provider.sender(), toNano('0.5'));
    // const mint: TopUp = {
    //     $$type: 'TopUp',
    //     queryId: 0n,
    // };

    // await provider.sender().send(
    //     {
    //         value: toNano("0.2"),
    //         to: fossFi.address,
    //         sendMode: SendMode.PAY_GAS_SEPARATELY,
    //         init: fossFi.init,
    //         body: beginCell()
    //             .store(
    //                 storeTopUp(mint),
    //             )
    //             .endCell(),
    //     }
    // )

    // await provider.waitForDeploy(fossFi.address);

    // run methods on `fossFi`==============================================================

    const network = getNetworkFromEnv()
    console.log(`Running deploy script for ${network} network and for Shard Jetton Minter`)
    console.log(
        "Make sure to send txn from following wallet:. \n" +
        deployerAddress.toString({ testOnly: true })
    )
    printSeparator()

    try {
        const fs = await import("fs/promises")
        const outFile = `${process.cwd()}/scripts/consts.ts`
        const address = fossFi.address.toString()
        const content = `// Auto-generated by shard.deploy.ts\nexport const FI_ADDRESS = "${address}"\n`
        await fs.writeFile(outFile, content, "utf8")
        console.log("Saved fossFi address const to", outFile)
    } catch (err) {
        console.warn("Failed to save fossFi address:", err)
    }
    const link = getJettonHttpLink(network, fossFi.address, "tonviewer")
    console.log(`You can soon check your deployed contract at ${link}`)
    console.log(`Jetton Minter deployed successfully!`);
}
